package com.ridechat.core

import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets

/** Protocol errors are reported as an [IllegalArgumentException] so callers can reject a peer. */
class ProtocolException(message: String) : IllegalArgumentException(message)

enum class ResumeRole {
    HOST,
    MEMBER,
}

/** The small control vocabulary exchanged over a verified Nearby connection. */
sealed class Control {
    data class Hello(
        val rideId: String,
        val senderId: String,
    ) : Control()

    data class Welcome(
        val rideId: String,
        val senderId: String,
        val resumeSecret: ByteArray,
    ) : Control()

    data class Members(
        val rideId: String,
        val memberIds: List<String>,
    ) : Control()

    data class Ready(
        val rideId: String,
        val senderId: String,
    ) : Control()

    data class Mute(
        val rideId: String,
        val senderId: String,
        val muted: Boolean,
    ) : Control()

    data class Ping(val nonce: Long) : Control()

    data class Pong(val nonce: Long) : Control()

    /** [nonce] is the nonce generated by the sender of this message. */
    data class ResumeHello(
        val rideId: String,
        val senderId: String,
        val nonce: ByteArray,
        val role: ResumeRole,
        val sessionToken: ByteArray,
    ) : Control()

    /** [nonce] is the fresh challenge nonce generated by the challenge sender. */
    data class Challenge(
        val rideId: String,
        val senderId: String,
        val nonce: ByteArray,
        val role: ResumeRole,
        val sessionToken: ByteArray,
    ) : Control()

    /** [nonce] is the proof sender's nonce; the receiver supplies its stored peer nonce to HMAC verification. */
    data class Proof(
        val rideId: String,
        val senderId: String,
        val nonce: ByteArray,
        val proof: ByteArray,
        val role: ResumeRole,
        val sessionToken: ByteArray,
    ) : Control()

    data class Accepted(
        val rideId: String,
        val senderId: String,
    ) : Control()

    data class Leave(
        val rideId: String,
        val senderId: String,
    ) : Control()

    data class End(val rideId: String) : Control()
}

/** A single encoded Opus frame. The payload is an Opus packet, not PCM. */
data class AudioFrame(
    val rideId: String,
    val senderId: String,
    val generation: Long,
    val sequence: Long,
    val sampleTime: Long,
    val payload: ByteArray,
)

object ProtocolLimits {
    const val VERSION: Int = 1
    const val MAX_CONTROL_BYTES: Int = 8 * 1024
    const val MAX_AUDIO_PAYLOAD_BYTES: Int = 2 * 1024
    const val MAX_AUDIO_FRAME_BODY_BYTES: Int = 2 * 1024 + 256
    const val MAX_AUDIO_STREAM_BUFFER_BYTES: Int = 16 * 1024
    const val MAX_RIDE_ID_BYTES: Int = 64
    const val MAX_SENDER_ID_BYTES: Int = 64
    const val MAX_MEMBER_ID_BYTES: Int = 64
    const val MAX_MEMBERS: Int = 4
    const val MAX_TOKEN_BYTES: Int = 256
    const val NONCE_BYTES: Int = 32
    const val RESUME_SECRET_BYTES: Int = 32
    const val PROOF_BYTES: Int = 32
}

/**
 * Version 1 wire codec. Integers are big-endian. A control value is one complete
 * payload. An audio value is a 4-byte body length followed by one complete body.
 */
object WireCodec {
    private const val CONTROL_HELLO = 1
    private const val CONTROL_WELCOME = 2
    private const val CONTROL_MEMBERS = 3
    private const val CONTROL_READY = 4
    private const val CONTROL_MUTE = 5
    private const val CONTROL_PING = 6
    private const val CONTROL_PONG = 7
    private const val CONTROL_RESUME_HELLO = 8
    private const val CONTROL_CHALLENGE = 9
    private const val CONTROL_PROOF = 10
    private const val CONTROL_ACCEPTED = 11
    private const val CONTROL_LEAVE = 12
    private const val CONTROL_END = 13

    private const val AUDIO_KIND = 1

    fun encodeControl(control: Control): ByteArray {
        val body = ByteArrayOutputStream()
        DataOutputStream(body).use { output ->
            output.writeByte(ProtocolLimits.VERSION)
            when (control) {
                is Control.Hello -> {
                    output.writeByte(CONTROL_HELLO)
                    writeRideAndSender(output, control.rideId, control.senderId)
                }

                is Control.Welcome -> {
                    output.writeByte(CONTROL_WELCOME)
                    writeRideAndSender(output, control.rideId, control.senderId)
                    writeFixedBytes(output, control.resumeSecret, ProtocolLimits.RESUME_SECRET_BYTES, "resume secret")
                }

                is Control.Members -> {
                    output.writeByte(CONTROL_MEMBERS)
                    writeRide(output, control.rideId)
                    if (control.memberIds.size !in 1..ProtocolLimits.MAX_MEMBERS) {
                        throw ProtocolException("member count out of bounds")
                    }
                    val ids = control.memberIds.map { validateText(it, ProtocolLimits.MAX_MEMBER_ID_BYTES, "member ID") }
                    if (ids.distinct().size != ids.size) throw ProtocolException("duplicate member ID")
                    output.writeByte(ids.size)
                    ids.forEach { writeText(output, it, ProtocolLimits.MAX_MEMBER_ID_BYTES, "member ID") }
                }

                is Control.Ready -> {
                    output.writeByte(CONTROL_READY)
                    writeRideAndSender(output, control.rideId, control.senderId)
                }

                is Control.Mute -> {
                    output.writeByte(CONTROL_MUTE)
                    writeRideAndSender(output, control.rideId, control.senderId)
                    output.writeByte(if (control.muted) 1 else 0)
                }

                is Control.Ping -> {
                    output.writeByte(CONTROL_PING)
                    output.writeLong(control.nonce)
                }

                is Control.Pong -> {
                    output.writeByte(CONTROL_PONG)
                    output.writeLong(control.nonce)
                }

                is Control.ResumeHello -> {
                    output.writeByte(CONTROL_RESUME_HELLO)
                    writeResumeFields(output, control.rideId, control.senderId, control.nonce, control.role, control.sessionToken)
                }

                is Control.Challenge -> {
                    output.writeByte(CONTROL_CHALLENGE)
                    writeResumeFields(output, control.rideId, control.senderId, control.nonce, control.role, control.sessionToken)
                }

                is Control.Proof -> {
                    output.writeByte(CONTROL_PROOF)
                    writeRideAndSender(output, control.rideId, control.senderId)
                    writeFixedBytes(output, control.nonce, ProtocolLimits.NONCE_BYTES, "resume nonce")
                    writeFixedBytes(output, control.proof, ProtocolLimits.PROOF_BYTES, "resume proof")
                    output.writeByte(control.role.ordinal)
                    writeBoundedBytes(output, control.sessionToken, ProtocolLimits.MAX_TOKEN_BYTES, "session token", nonEmpty = true)
                }

                is Control.Accepted -> {
                    output.writeByte(CONTROL_ACCEPTED)
                    writeRideAndSender(output, control.rideId, control.senderId)
                }

                is Control.Leave -> {
                    output.writeByte(CONTROL_LEAVE)
                    writeRideAndSender(output, control.rideId, control.senderId)
                }

                is Control.End -> {
                    output.writeByte(CONTROL_END)
                    writeRide(output, control.rideId)
                }
            }
        }
        return body.toByteArray().also { encoded ->
            if (encoded.size > ProtocolLimits.MAX_CONTROL_BYTES) {
                throw ProtocolException("control message exceeds ${ProtocolLimits.MAX_CONTROL_BYTES} bytes")
            }
        }
    }

    fun decodeControl(encoded: ByteArray): Control {
        if (encoded.isEmpty()) throw ProtocolException("empty control message")
        if (encoded.size > ProtocolLimits.MAX_CONTROL_BYTES) {
            throw ProtocolException("control message exceeds ${ProtocolLimits.MAX_CONTROL_BYTES} bytes")
        }
        val cursor = Cursor(encoded)
        val version = cursor.readUnsignedByte("version")
        if (version != ProtocolLimits.VERSION) throw ProtocolException("unsupported protocol version: $version")
        val type = cursor.readUnsignedByte("control type")
        val result = when (type) {
            CONTROL_HELLO -> Control.Hello(cursor.readRide(), cursor.readSender())
            CONTROL_WELCOME -> Control.Welcome(
                cursor.readRide(),
                cursor.readSender(),
                cursor.readFixedBytes(ProtocolLimits.RESUME_SECRET_BYTES, "resume secret"),
            )

            CONTROL_MEMBERS -> {
                val rideId = cursor.readRide()
                val count = cursor.readUnsignedByte("member count")
                if (count !in 1..ProtocolLimits.MAX_MEMBERS) throw ProtocolException("member count out of bounds")
                val ids = ArrayList<String>(count)
                repeat(count) { ids += cursor.readText(ProtocolLimits.MAX_MEMBER_ID_BYTES, "member ID") }
                if (ids.distinct().size != ids.size) throw ProtocolException("duplicate member ID")
                Control.Members(rideId, ids)
            }

            CONTROL_READY -> Control.Ready(cursor.readRide(), cursor.readSender())
            CONTROL_MUTE -> {
                val rideId = cursor.readRide()
                val senderId = cursor.readSender()
                val muted = when (cursor.readUnsignedByte("mute state")) {
                    0 -> false
                    1 -> true
                    else -> throw ProtocolException("invalid mute state")
                }
                Control.Mute(rideId, senderId, muted)
            }

            CONTROL_PING -> Control.Ping(cursor.readLong("ping nonce"))
            CONTROL_PONG -> Control.Pong(cursor.readLong("pong nonce"))
            CONTROL_RESUME_HELLO -> readResumeHello(cursor)
            CONTROL_CHALLENGE -> readChallenge(cursor)
            CONTROL_PROOF -> Control.Proof(
                cursor.readRide(),
                cursor.readSender(),
                cursor.readFixedBytes(ProtocolLimits.NONCE_BYTES, "resume nonce"),
                cursor.readFixedBytes(ProtocolLimits.PROOF_BYTES, "resume proof"),
                cursor.readRole(),
                cursor.readToken(),
            )

            CONTROL_ACCEPTED -> Control.Accepted(cursor.readRide(), cursor.readSender())
            CONTROL_LEAVE -> Control.Leave(cursor.readRide(), cursor.readSender())
            CONTROL_END -> Control.End(cursor.readRide())
            else -> throw ProtocolException("unknown control type: $type")
        }
        cursor.requireEnd()
        return result
    }

    fun encodeAudioFrame(frame: AudioFrame): ByteArray {
        validateAudioFrame(frame)
        val body = ByteArrayOutputStream()
        DataOutputStream(body).use { output ->
            output.writeByte(ProtocolLimits.VERSION)
            output.writeByte(AUDIO_KIND)
            writeText(output, frame.rideId, ProtocolLimits.MAX_RIDE_ID_BYTES, "ride ID")
            writeText(output, frame.senderId, ProtocolLimits.MAX_SENDER_ID_BYTES, "sender ID")
            output.writeLong(frame.generation)
            output.writeLong(frame.sequence)
            output.writeLong(frame.sampleTime)
            writeBoundedBytes(output, frame.payload, ProtocolLimits.MAX_AUDIO_PAYLOAD_BYTES, "audio payload", nonEmpty = true)
        }
        val bodyBytes = body.toByteArray()
        if (bodyBytes.size > ProtocolLimits.MAX_AUDIO_FRAME_BODY_BYTES) {
            throw ProtocolException("audio frame exceeds the bounded frame size")
        }
        val encoded = ByteArray(4 + bodyBytes.size)
        ByteBuffer.wrap(encoded).order(ByteOrder.BIG_ENDIAN).putInt(bodyBytes.size).put(bodyBytes)
        return encoded
    }

    fun decodeAudioFrame(encoded: ByteArray): AudioFrame {
        if (encoded.size < 4) throw ProtocolException("truncated audio frame length")
        val declaredLength = ByteBuffer.wrap(encoded, 0, 4).order(ByteOrder.BIG_ENDIAN).int
        if (declaredLength <= 0 || declaredLength > ProtocolLimits.MAX_AUDIO_FRAME_BODY_BYTES) {
            throw ProtocolException("audio frame length out of bounds")
        }
        if (encoded.size != declaredLength + 4) throw ProtocolException("audio frame truncation or trailing bytes")
        val cursor = Cursor(encoded, 4, declaredLength)
        val version = cursor.readUnsignedByte("version")
        if (version != ProtocolLimits.VERSION) throw ProtocolException("unsupported protocol version: $version")
        val kind = cursor.readUnsignedByte("audio kind")
        if (kind != AUDIO_KIND) throw ProtocolException("unknown audio frame kind: $kind")
        val frame = AudioFrame(
            rideId = cursor.readRide(),
            senderId = cursor.readSender(),
            generation = cursor.readLong("generation"),
            sequence = cursor.readLong("sequence"),
            sampleTime = cursor.readLong("sample timestamp"),
            payload = cursor.readBoundedBytes(ProtocolLimits.MAX_AUDIO_PAYLOAD_BYTES, "audio payload", nonEmpty = true),
        )
        cursor.requireEnd()
        validateAudioFrame(frame)
        return frame
    }

    private fun readResumeHello(cursor: Cursor): Control.ResumeHello {
        val (rideId, senderId, nonce, role, token) = readResumeFields(cursor)
        return Control.ResumeHello(rideId, senderId, nonce, role, token)
    }

    private fun readChallenge(cursor: Cursor): Control.Challenge {
        val (rideId, senderId, nonce, role, token) = readResumeFields(cursor)
        return Control.Challenge(rideId, senderId, nonce, role, token)
    }

    private fun writeRideAndSender(output: DataOutputStream, rideId: String, senderId: String) {
        writeRide(output, rideId)
        writeText(output, senderId, ProtocolLimits.MAX_SENDER_ID_BYTES, "sender ID")
    }

    private fun writeRide(output: DataOutputStream, rideId: String) {
        writeText(output, rideId, ProtocolLimits.MAX_RIDE_ID_BYTES, "ride ID")
    }

    private fun writeResumeFields(
        output: DataOutputStream,
        rideId: String,
        senderId: String,
        nonce: ByteArray,
        role: ResumeRole,
        sessionToken: ByteArray,
    ) {
        writeRideAndSender(output, rideId, senderId)
        writeFixedBytes(output, nonce, ProtocolLimits.NONCE_BYTES, "resume nonce")
        output.writeByte(role.ordinal)
        writeBoundedBytes(output, sessionToken, ProtocolLimits.MAX_TOKEN_BYTES, "session token", nonEmpty = true)
    }

    private fun readResumeFields(cursor: Cursor): ResumeFields {
        return ResumeFields(
            rideId = cursor.readRide(),
            senderId = cursor.readSender(),
            nonce = cursor.readFixedBytes(ProtocolLimits.NONCE_BYTES, "resume nonce"),
            role = cursor.readRole(),
            sessionToken = cursor.readToken(),
        )
    }

    private data class ResumeFields(
        val rideId: String,
        val senderId: String,
        val nonce: ByteArray,
        val role: ResumeRole,
        val sessionToken: ByteArray,
    )

    private fun validateAudioFrame(frame: AudioFrame) {
        validateText(frame.rideId, ProtocolLimits.MAX_RIDE_ID_BYTES, "ride ID")
        validateText(frame.senderId, ProtocolLimits.MAX_SENDER_ID_BYTES, "sender ID")
        if (frame.generation < 0) throw ProtocolException("negative connection generation")
        if (frame.sequence < 0) throw ProtocolException("negative audio sequence")
        if (frame.sampleTime < 0) throw ProtocolException("negative audio sample timestamp")
        validateBytes(frame.payload, ProtocolLimits.MAX_AUDIO_PAYLOAD_BYTES, "audio payload", nonEmpty = true)
    }

    private fun writeText(output: DataOutputStream, value: String, maxBytes: Int, label: String) {
        val validated = validateText(value, maxBytes, label)
        val bytes = validated.toByteArray(StandardCharsets.UTF_8)
        output.writeShort(bytes.size)
        output.write(bytes)
    }

    private fun writeBoundedBytes(
        output: DataOutputStream,
        value: ByteArray,
        maxBytes: Int,
        label: String,
        nonEmpty: Boolean,
    ) {
        validateBytes(value, maxBytes, label, nonEmpty)
        output.writeShort(value.size)
        output.write(value)
    }

    private fun writeFixedBytes(output: DataOutputStream, value: ByteArray, expectedBytes: Int, label: String) {
        if (value.size != expectedBytes) throw ProtocolException("$label must be $expectedBytes bytes")
        output.write(value)
    }

    private fun validateText(value: String, maxBytes: Int, label: String): String {
        if (value.isEmpty()) throw ProtocolException("$label must not be empty")
        if (value.indexOf('\u0000') >= 0) throw ProtocolException("$label contains NUL")
        val bytes = value.toByteArray(StandardCharsets.UTF_8)
        if (bytes.size > maxBytes) throw ProtocolException("$label exceeds $maxBytes UTF-8 bytes")
        return value
    }

    private fun validateBytes(value: ByteArray, maxBytes: Int, label: String, nonEmpty: Boolean) {
        if (nonEmpty && value.isEmpty()) throw ProtocolException("$label must not be empty")
        if (value.size > maxBytes) throw ProtocolException("$label exceeds $maxBytes bytes")
    }

    private class Cursor(
        private val bytes: ByteArray,
        start: Int = 0,
        length: Int = bytes.size - start,
    ) {
        private var position = start
        private val end = start + length

        fun readUnsignedByte(label: String): Int {
            requireAvailable(1, label)
            return bytes[position++].toInt() and 0xff
        }

        fun readLong(label: String): Long {
            requireAvailable(8, label)
            val value = ByteBuffer.wrap(bytes, position, 8).order(ByteOrder.BIG_ENDIAN).long
            position += 8
            return value
        }

        fun readRide(): String = readText(ProtocolLimits.MAX_RIDE_ID_BYTES, "ride ID")

        fun readSender(): String = readText(ProtocolLimits.MAX_SENDER_ID_BYTES, "sender ID")

        fun readRole(): ResumeRole {
            return when (readUnsignedByte("resume role")) {
                0 -> ResumeRole.HOST
                1 -> ResumeRole.MEMBER
                else -> throw ProtocolException("invalid resume role")
            }
        }

        fun readToken(): ByteArray = readBoundedBytes(ProtocolLimits.MAX_TOKEN_BYTES, "session token", nonEmpty = true)

        fun readFixedBytes(size: Int, label: String): ByteArray {
            requireAvailable(size, label)
            val value = bytes.copyOfRange(position, position + size)
            position += size
            return value
        }

        fun readBoundedBytes(maxBytes: Int, label: String, nonEmpty: Boolean): ByteArray {
            val length = readUnsignedShort("$label length")
            if (length > maxBytes || (nonEmpty && length == 0)) {
                throw ProtocolException("$label length out of bounds")
            }
            requireAvailable(length, label)
            val value = bytes.copyOfRange(position, position + length)
            position += length
            return value
        }

        fun readText(maxBytes: Int, label: String): String {
            val bytesValue = readBoundedBytes(maxBytes, label, nonEmpty = true)
            return try {
                StandardCharsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(bytesValue))
                    .toString()
                    .also { value ->
                        if (value.indexOf('\u0000') >= 0) throw ProtocolException("$label contains NUL")
                    }
            } catch (_: CharacterCodingException) {
                throw ProtocolException("$label is not valid UTF-8")
            }
        }

        fun requireEnd() {
            if (position != end) throw ProtocolException("trailing bytes in message")
        }

        private fun readUnsignedShort(label: String): Int {
            requireAvailable(2, label)
            val value = ByteBuffer.wrap(bytes, position, 2).order(ByteOrder.BIG_ENDIAN).short.toInt() and 0xffff
            position += 2
            return value
        }

        private fun requireAvailable(count: Int, label: String) {
            if (count < 0 || end - position < count) throw ProtocolException("truncated $label")
        }
    }
}

/** Incremental parser for the length-delimited audio stream. */
class AudioFrameStreamDecoder {
    private var buffered = ByteArray(0)

    fun feed(chunk: ByteArray): List<AudioFrame> {
        if (chunk.isEmpty()) return emptyList()
        if (chunk.size > ProtocolLimits.MAX_AUDIO_STREAM_BUFFER_BYTES - buffered.size) {
            throw ProtocolException("audio stream buffer exceeds its bound")
        }
        buffered += chunk
        val frames = ArrayList<AudioFrame>()
        var offset = 0
        while (buffered.size - offset >= 4) {
            val length = ByteBuffer.wrap(buffered, offset, 4).order(ByteOrder.BIG_ENDIAN).int
            if (length <= 0 || length > ProtocolLimits.MAX_AUDIO_FRAME_BODY_BYTES) {
                throw ProtocolException("audio frame length out of bounds")
            }
            val completeLength = 4 + length
            if (buffered.size - offset < completeLength) break
            frames += WireCodec.decodeAudioFrame(buffered.copyOfRange(offset, offset + completeLength))
            offset += completeLength
        }
        if (offset > 0) buffered = buffered.copyOfRange(offset, buffered.size)
        if (buffered.size > ProtocolLimits.MAX_AUDIO_STREAM_BUFFER_BYTES) {
            throw ProtocolException("audio stream buffer exceeds its bound")
        }
        return frames
    }

    /** Call when the transport reports end-of-stream; a partial frame is an error. */
    fun finish() {
        if (buffered.isNotEmpty()) throw ProtocolException("truncated audio stream")
    }

    fun reset() {
        buffered = ByteArray(0)
    }
}
